import type { AiTaskType } from '../types/ai-task-type.ts';
import type { AiAdapterRequest } from '../types/ai-request.ts';
import type { AiProviderAdapter } from '../types/ai-adapter.ts';
import type { AiProviderResult } from '../types/ai-response.ts';

export interface MockAiAdapterOptions {
  handlers?: Partial<Record<AiTaskType, (request: AiAdapterRequest) => Promise<AiProviderResult> | AiProviderResult>>;
}

export function createMockAiAdapter(options: MockAiAdapterOptions = {}): AiProviderAdapter {
  return {
    provider: 'mock',
    async run(request: AiAdapterRequest): Promise<AiProviderResult> {
      const taskHandler = options.handlers?.[request.taskType];
      if (taskHandler) {
        return taskHandler(request);
      }
      return {
        ok: true,
        data: {
          summary: 'Mock response generated by ai-gateway.',
          taskType: request.taskType,
          requestId: request.requestId
        }
      };
    }
  };
}
